project:
  output-dir: Outputs

format:
  html:
    theme: flatly 
    toc: true
    number-sections: false


title-block-banner: true

execute:
  echo: false
  warning: false
  message: false
  results: false