project:
  output-dir: Outputs

format:
  html:
    toc: true
    number-sections: false
  pdf:
    toc: true
    number-sections: false
    include-in-header:
      - text: \usepackage{float}

execute:
  echo: false
  warning: false
  message: false
  results: false