project:
  type: website
  output-dir: docs  # GitHub Pages expects this

format:
  html:
    toc: true
    number-sections: true
  pdf:
    toc: true
    number-sections: true
    include-in-header:
      - text: \usepackage{float}

website:
  title: "Empirical Project"
  page-navigation: true
  navbar: false

execute:
  echo: false
  warning: false
  message: false
  results: false