project:
  output-dir: Outputs

format:
  html:
    theme: flatly
    css: styles.css         
    toc: true
    number-sections: false
    csl: References/apa.csl
    bibliography: References/references.bib
title-block-banner: true

execute:
  echo: false
  warning: false
  message: false
  results: false
